{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMuoA5PgxXBifRbDzbBHyfH"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "**Этап 1.**\n",
        "Сбор данных\n",
        "• Выберите как минимум два источника данных и получите к ним доступ:\n",
        "– API VirusTotal — для проверки IP, файлов или доменов;\n",
        "– API Vulners — для поиска уязвимостей;\n",
        "– логи Suricata — события сетевой безопасности.\n",
        "• При необходимости создайте папку с логами или подготовьте примеры данных.\n",
        "\n",
        "**Этап 2.**\n",
        "Анализ данных\n",
        "• Напишите скрипт, который:\n",
        "– выполняет запросы к API или загружает логи;\n",
        "– анализирует полученные данные: ищет опасные уязвимости (например, с высоким CVSS-баллом), определяет подозрительные IP или трафик (например, частые DNS-запросы).\n",
        "• Для анализа используйте библиотеки pandas, json, requests.\n",
        "\n",
        "\n",
        "**Этап 3.**\n",
        "Реагирование на угрозы\n",
        "• Добавьте логику реагирования. Если найдена угроза,\n",
        "– выведите сообщение о найденной угрозе или сымитируйте блокировку IP\n",
        "– отправьте уведомления в Telegram или на email.\n",
        "• Реальное взаимодействие с системами блокировки не требуется, достаточно имитации — вывода сообщения в консоль.\n",
        "\n",
        "\n",
        "**Этап 4.**\n",
        "Формирование отчёта и визуализация\n",
        "• Сохраните результаты анализа в формате .json или .csv.\n",
        "• Постройте один график по результатам анализа, например, топ-5 IP или распределение CVSS-баллов. Сохраните график в файл .png."
      ],
      "metadata": {
        "id": "rWoeGQUSrzIP"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "i8SjFAtSn6TR",
        "outputId": "2f53e94d-dab4-449f-cd01-b2ac9ef78f6e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            " СИСТЕМА МОНИТОРИНГА И РЕАГИРОВАНИЯ НА УГРОЗЫ \n",
            "\n",
            "Используемые источники данных:\n",
            "1. VirusTotal API - анализ репутации IP\n",
            "2. HTTP Analysis - анализ веб-трафика\n",
            "3. Security Logs - анализ логов Windows/DNS/HTTP \n",
            "\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "WARNING:__main__:РЕАГИРОВАНИЕ: Блокировка IP 185.220.101.33 (подтверждено VirusTotal: 15 детектов)\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 4b72bc44\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе f45090ff\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 2681db44\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 4a3272e0\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 0fb1ba40\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 0c9c9769\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Блокировка IP 10.0.2.15 (подтверждено VirusTotal: 8 детектов)\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Мониторинг активности 192.168.1.50\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Мониторинг активности 192.168.1.100\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 9eeaa1d6\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Уведомление SOC об угрозе 643de8a7\n",
            "WARNING:__main__:РЕАГИРОВАНИЕ: Мониторинг активности 203.0.113.45\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "РЕЗУЛЬТАТЫ ВЫПОЛНЕНИЯ:\n",
            "Обнаружено угроз: 13\n",
            "Заблокировано IP: 2\n",
            "Заблокированные адреса: 185.220.101.33, 10.0.2.15\n",
            "Создано файлов отчета: 3\n"
          ]
        }
      ],
      "source": [
        "\"\"\"\n",
        "Автоматизированный мониторинг и реагирование на угрозы:\n",
        "1. VirusTotal API (API и анализ данных)\n",
        "2. Requests для анализа HTTP (Эксплойты)\n",
        "3. Анализ логов Windows/DNS с pandas\n",
        "\"\"\"\n",
        "\n",
        "import json\n",
        "import requests\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import hashlib\n",
        "import ipaddress\n",
        "import socket\n",
        "import re\n",
        "from datetime import datetime, timedelta\n",
        "import time\n",
        "import os\n",
        "import sys\n",
        "from typing import Dict, List, Any, Optional\n",
        "import logging\n",
        "from dataclasses import dataclass\n",
        "from urllib.parse import urlparse\n",
        "import warnings\n",
        "\n",
        "# Настройка логирования\n",
        "logging.basicConfig(\n",
        "    level=logging.INFO,\n",
        "    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'\n",
        ")\n",
        "logger = logging.getLogger(__name__)\n",
        "\n",
        "@dataclass\n",
        "class Threat:\n",
        "    #Класс для представления обнаруженной угрозы\n",
        "    id: str\n",
        "    type: str\n",
        "    severity: str\n",
        "    source_ip: str\n",
        "    target: str\n",
        "    description: str\n",
        "    timestamp: datetime\n",
        "    confidence: int = 0\n",
        "    indicators: List[str] = None\n",
        "    source_data: str = \"\"\n",
        "\n",
        "    def __post_init__(self):\n",
        "        if self.indicators is None:\n",
        "            self.indicators = []\n",
        "\n",
        "class SecurityMonitor:\n",
        "    def __init__(self, use_demo: bool = True):\n",
        "         #Инициализация системы мониторинга\n",
        "        self.use_demo = use_demo\n",
        "        self.detected_threats = []\n",
        "        self.blocked_ips = []\n",
        "\n",
        "        # Конфигурация\n",
        "        self.config = {\n",
        "            'virustotal_api_key': '5018c3a2f8a7d6e5c4b3a2918b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9',  # Демо-ключ\n",
        "            'min_malicious_score': 3,\n",
        "            'suspicious_ports': [4444, 31337, 6667, 1337, 8080, 8888],\n",
        "            'suspicious_user_agents': [\n",
        "                'sqlmap', 'nikto', 'metasploit', 'nmap',\n",
        "                'hydra', 'john', 'aircrack', 'wireshark'\n",
        "            ],\n",
        "            'suspicious_event_ids': [4625, 4648, 1102, 4720, 4728, 4732, 4740],\n",
        "            'high_dns_query_threshold': 50,\n",
        "            'max_failed_logins': 5\n",
        "        }\n",
        "\n",
        "        logger.info(\"Инициализация системы мониторинга безопасности\")\n",
        "\n",
        "    # VirusTotal API\n",
        "\n",
        "    def check_virustotal(self, ip_address: str) -> Dict[str, Any]:\n",
        "\n",
        "        # Проверка IP через VirusTotal API с публичным API ключом для демонстрации\n",
        "        try:\n",
        "            if self.use_demo:\n",
        "                return self._demo_virustotal_check(ip_address)\n",
        "\n",
        "            # Реальный запрос к VirusTotal API\n",
        "            url = f\"https://www.virustotal.com/api/v3/ip_addresses/{ip_address}\"\n",
        "            headers = {\n",
        "                \"x-apikey\": self.config['virustotal_api_key'],\n",
        "                \"User-Agent\": \"SecurityMonitor/1.0\"\n",
        "            }\n",
        "\n",
        "            logger.info(f\"Запрос к VirusTotal API для IP: {ip_address}\")\n",
        "            response = requests.get(url, headers=headers, timeout=15)\n",
        "\n",
        "            if response.status_code == 200:\n",
        "                data = response.json()\n",
        "                stats = data.get('data', {}).get('attributes', {}).get('last_analysis_stats', {})\n",
        "\n",
        "                return {\n",
        "                    'success': True,\n",
        "                    'malicious': stats.get('malicious', 0),\n",
        "                    'suspicious': stats.get('suspicious', 0),\n",
        "                    'harmless': stats.get('harmless', 0),\n",
        "                    'undetected': stats.get('undetected', 0),\n",
        "                    'asn': data.get('data', {}).get('attributes', {}).get('asn', 'Unknown'),\n",
        "                    'country': data.get('data', {}).get('attributes', {}).get('country', 'Unknown'),\n",
        "                    'source': 'VirusTotal API'\n",
        "                }\n",
        "            elif response.status_code == 401:\n",
        "                logger.warning(\"VirusTotal API ключ недействителен, используется демо-режим\")\n",
        "                return self._demo_virustotal_check(ip_address)\n",
        "            else:\n",
        "                logger.warning(f\"VirusTotal API ошибка {response.status_code}\")\n",
        "                return {'success': False, 'error': f\"HTTP {response.status_code}\"}\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка VirusTotal API: {e}\")\n",
        "            return self._demo_virustotal_check(ip_address)\n",
        "\n",
        "    def _demo_virustotal_check(self, ip_address: str) -> Dict[str, Any]:\n",
        "        time.sleep(0.3)\n",
        "\n",
        "        # Демо-данные на основе реальных вредоносных IP\n",
        "        demo_data = {\n",
        "            \"185.220.101.33\": {\"malicious\": 15, \"suspicious\": 3, \"reputation\": -5, \"tags\": [\"malware\", \"c2\"]},\n",
        "            \"45.155.205.233\": {\"malicious\": 12, \"suspicious\": 2, \"reputation\": -4, \"tags\": [\"phishing\"]},\n",
        "            \"192.168.1.100\": {\"malicious\": 0, \"suspicious\": 0, \"reputation\": 0, \"tags\": []},\n",
        "            \"10.0.2.15\": {\"malicious\": 8, \"suspicious\": 2, \"reputation\": -3, \"tags\": [\"suspicious\"]},\n",
        "            \"8.8.8.8\": {\"malicious\": 0, \"suspicious\": 0, \"reputation\": 100, \"tags\": []}\n",
        "        }\n",
        "\n",
        "        if ip_address in demo_data:\n",
        "            data = demo_data[ip_address]\n",
        "        else:\n",
        "            # Определяем тип IP для демо-данных\n",
        "            try:\n",
        "                ip = ipaddress.ip_address(ip_address)\n",
        "                if ip.is_private:\n",
        "                    malicious = 0\n",
        "                    suspicious = 0\n",
        "                elif ip_address.startswith(('10.', '172.', '192.168.')):\n",
        "                    malicious = 0\n",
        "                    suspicious = 0\n",
        "                else:\n",
        "                    # Внешние IP могут быть подозрительными\n",
        "                    import random\n",
        "                    malicious = random.randint(0, 2)\n",
        "                    suspicious = random.randint(0, 1)\n",
        "            except:\n",
        "                malicious = 0\n",
        "                suspicious = 0\n",
        "\n",
        "            data = {\n",
        "                \"malicious\": malicious,\n",
        "                \"suspicious\": suspicious,\n",
        "                \"reputation\": 0 if malicious == 0 else -malicious,\n",
        "                \"tags\": []\n",
        "            }\n",
        "\n",
        "        return {\n",
        "            'success': True,\n",
        "            'malicious': data['malicious'],\n",
        "            'suspicious': data['suspicious'],\n",
        "            'reputation': data['reputation'],\n",
        "            'tags': data['tags'],\n",
        "            'asn': 'AS12345',\n",
        "            'country': 'US',\n",
        "            'source': 'VirusTotal (Demo)'\n",
        "        }\n",
        "\n",
        "    #  Анализ HTTP/Web\n",
        "\n",
        "    def analyze_http_traffic(self, target_url: str = None) -> Dict[str, Any]:\n",
        "        \"\"\"\n",
        "        Анализ HTTP трафика с помощью requests\n",
        "        Имитация анализа веб-приложений на уязвимости\n",
        "        \"\"\"\n",
        "        try:\n",
        "            threats = []\n",
        "            analysis_results = {\n",
        "                'success': True,\n",
        "                'target': target_url or 'http://example.com',\n",
        "                'vulnerabilities_found': [],\n",
        "                'threats': [],\n",
        "                'source': 'HTTP Analysis'\n",
        "            }\n",
        "\n",
        "            if target_url:\n",
        "                # Проверка на SQL инъекции\n",
        "                sql_payloads = [\"' OR '1'='1\", \"' UNION SELECT null--\", \"'; DROP TABLE users--\"]\n",
        "\n",
        "                for payload in sql_payloads:\n",
        "                    test_url = f\"{target_url}?id={payload}\"\n",
        "                    try:\n",
        "                        response = requests.get(test_url, timeout=10)\n",
        "\n",
        "                        # Простая проверка на SQL инъекцию\n",
        "                        sql_errors = [\n",
        "                            \"sql syntax\", \"mysql_fetch\", \"ORA-\", \"PostgreSQL\",\n",
        "                            \"SQLite\", \"Microsoft OLE DB\", \"ODBC\", \"JDBC\"\n",
        "                        ]\n",
        "\n",
        "                        for error in sql_errors:\n",
        "                            if error.lower() in response.text.lower():\n",
        "                                threat_id = hashlib.md5(f\"sql-{target_url}-{payload}\".encode()).hexdigest()[:8]\n",
        "                                threat = Threat(\n",
        "                                    id=threat_id,\n",
        "                                    type=\"SQL Injection\",\n",
        "                                    severity=\"High\",\n",
        "                                    source_ip=\"Scanner\",\n",
        "                                    target=target_url,\n",
        "                                    description=f\"Возможная SQL инъекция обнаружена с payload: {payload}\",\n",
        "                                    timestamp=datetime.now(),\n",
        "                                    confidence=70,\n",
        "                                    source_data=\"HTTP Analysis\"\n",
        "                                )\n",
        "                                threats.append(threat)\n",
        "                                analysis_results['vulnerabilities_found'].append(\"SQL Injection\")\n",
        "                                break\n",
        "                    except:\n",
        "                        continue\n",
        "\n",
        "            # Анализ User-Agent строк (пример из эксплойтов)\n",
        "            suspicious_agents = self._check_suspicious_user_agents()\n",
        "            threats.extend(suspicious_agents)\n",
        "\n",
        "            # Проверка на XSS (кросс-сайтовый скриптинг)\n",
        "            xss_threats = self._check_xss_vulnerabilities(target_url)\n",
        "            threats.extend(xss_threats)\n",
        "\n",
        "            analysis_results['threats'] = threats\n",
        "            return analysis_results\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка анализа HTTP: {e}\")\n",
        "            return {'success': False, 'error': str(e), 'source': 'HTTP Analysis'}\n",
        "\n",
        "    def _check_suspicious_user_agents(self) -> List[Threat]:\n",
        "        \"\"\"Проверка на подозрительные User-Agent строки\"\"\"\n",
        "        threats = []\n",
        "\n",
        "        # Пример подозрительных User-Agent из логов\n",
        "        suspicious_logs = [\n",
        "            {\"ip\": \"192.168.1.100\", \"user_agent\": \"sqlmap/1.6#dev\", \"time\": \"2024-01-15 08:30:15\"},\n",
        "            {\"ip\": \"10.0.2.15\", \"user_agent\": \"Mozilla/5.00 (Nikto/2.1.6)\", \"time\": \"2024-01-15 09:15:22\"},\n",
        "            {\"ip\": \"203.0.113.45\", \"user_agent\": \"Metasploit\", \"time\": \"2024-01-15 10:45:33\"}\n",
        "        ]\n",
        "\n",
        "        for log in suspicious_logs:\n",
        "            for suspicious_agent in self.config['suspicious_user_agents']:\n",
        "                if suspicious_agent.lower() in log['user_agent'].lower():\n",
        "                    threat_id = hashlib.md5(f\"ua-{log['ip']}-{log['user_agent']}\".encode()).hexdigest()[:8]\n",
        "                    threat = Threat(\n",
        "                        id=threat_id,\n",
        "                        type=\"Suspicious User-Agent\",\n",
        "                        severity=\"Medium\",\n",
        "                        source_ip=log['ip'],\n",
        "                        target=\"Web Server\",\n",
        "                        description=f\"Подозрительный User-Agent обнаружен: {log['user_agent']}\",\n",
        "                        timestamp=datetime.now(),\n",
        "                        confidence=80,\n",
        "                        source_data=\"HTTP Logs\"\n",
        "                    )\n",
        "                    threats.append(threat)\n",
        "                    break\n",
        "\n",
        "        return threats\n",
        "\n",
        "    def _check_xss_vulnerabilities(self, target_url: str = None) -> List[Threat]:\n",
        "        \"\"\"Проверка на XSS уязвимости\"\"\"\n",
        "        threats = []\n",
        "\n",
        "        # Демо-данные XSS обнаружений\n",
        "        xss_payloads = [\n",
        "            {\"ip\": \"192.168.1.100\", \"payload\": \"<script>alert(1)</script>\", \"parameter\": \"search\"},\n",
        "            {\"ip\": \"10.0.2.15\", \"payload\": \"\\\"><img src=x onerror=alert(1)>\", \"parameter\": \"q\"}\n",
        "        ]\n",
        "\n",
        "        for xss in xss_payloads:\n",
        "            threat_id = hashlib.md5(f\"xss-{xss['ip']}-{xss['payload']}\".encode()).hexdigest()[:8]\n",
        "            threat = Threat(\n",
        "                id=threat_id,\n",
        "                type=\"XSS Attempt\",\n",
        "                severity=\"Medium\",\n",
        "                source_ip=xss['ip'],\n",
        "                target=target_url or \"Web Application\",\n",
        "                description=f\"Попытка XSS с payload: {xss['payload']} в параметре {xss['parameter']}\",\n",
        "                timestamp=datetime.now(),\n",
        "                confidence=75,\n",
        "                source_data=\"Web Analysis\"\n",
        "            )\n",
        "            threats.append(threat)\n",
        "\n",
        "        return threats\n",
        "\n",
        "    # ========== ИСТОЧНИК 3: Анализ логов с pandas ==========\n",
        "\n",
        "    def analyze_security_logs(self, log_data: Dict = None) -> Dict[str, Any]:\n",
        "\n",
        "        # Анализ логов безопасности с помощью pandas\n",
        "\n",
        "        try:\n",
        "            if log_data is None:\n",
        "                log_data = self._generate_demo_logs()\n",
        "\n",
        "            # Преобразуем в DataFrame для анализа\n",
        "            df_winevent = pd.DataFrame(log_data.get('winevent', []))\n",
        "            df_dns = pd.DataFrame(log_data.get('dns', []))\n",
        "            df_http = pd.DataFrame(log_data.get('http', []))\n",
        "\n",
        "            threats = []\n",
        "            analysis_summary = {\n",
        "                'success': True,\n",
        "                'total_logs': len(df_winevent) + len(df_dns) + len(df_http),\n",
        "                'threats_found': 0,\n",
        "                'log_types': {\n",
        "                    'winevent': len(df_winevent),\n",
        "                    'dns': len(df_dns),\n",
        "                    'http': len(df_http)\n",
        "                }\n",
        "            }\n",
        "\n",
        "            # 1. Анализ Windows Event Logs\n",
        "            if not df_winevent.empty:\n",
        "                winevent_threats = self._analyze_winevent_logs(df_winevent)\n",
        "                threats.extend(winevent_threats)\n",
        "\n",
        "            # 2. Анализ DNS логов\n",
        "            if not df_dns.empty:\n",
        "                dns_threats = self._analyze_dns_logs(df_dns)\n",
        "                threats.extend(dns_threats)\n",
        "\n",
        "            # 3. Анализ HTTP логов\n",
        "            if not df_http.empty:\n",
        "                http_threats = self._analyze_http_logs(df_http)\n",
        "                threats.extend(http_threats)\n",
        "\n",
        "            analysis_summary['threats_found'] = len(threats)\n",
        "            analysis_summary['threats'] = threats\n",
        "\n",
        "            return analysis_summary\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка анализа логов: {e}\")\n",
        "            return {'success': False, 'error': str(e)}\n",
        "\n",
        "    def _generate_demo_logs(self) -> Dict:\n",
        "        \"\"\"Генерация демо-логов для анализа\"\"\"\n",
        "        return {\n",
        "            'winevent': [\n",
        "                {\"timestamp\": \"2024-01-15 08:30:15\", \"event_id\": 4625, \"source_ip\": \"192.168.1.100\",\n",
        "                 \"user\": \"admin\", \"description\": \"Неудачная попытка входа\", \"count\": 3},\n",
        "                {\"timestamp\": \"2024-01-15 08:31:22\", \"event_id\": 4624, \"source_ip\": \"10.0.2.15\",\n",
        "                 \"user\": \"user1\", \"description\": \"Успешный вход\", \"count\": 1},\n",
        "                {\"timestamp\": \"2024-01-15 08:32:45\", \"event_id\": 4648, \"source_ip\": \"192.168.1.100\",\n",
        "                 \"user\": \"SYSTEM\", \"description\": \"Вход с использованием явных учётных данных\", \"count\": 1},\n",
        "                {\"timestamp\": \"2024-01-15 08:35:10\", \"event_id\": 1102, \"source_ip\": \"10.0.2.15\",\n",
        "                 \"user\": \"admin\", \"description\": \"Очистка журнала аудита\", \"count\": 1},\n",
        "                {\"timestamp\": \"2024-01-15 08:40:30\", \"event_id\": 4720, \"source_ip\": \"192.168.1.50\",\n",
        "                 \"user\": \"Administrator\", \"description\": \"Создание учётной записи\", \"count\": 1}\n",
        "            ],\n",
        "            'dns': [\n",
        "                {\"timestamp\": \"2024-01-15 09:00:00\", \"query\": \"demo-01\", \"src_ip\": \"192.168.1.100\", \"count\": 27},\n",
        "                {\"timestamp\": \"2024-01-15 09:01:00\", \"query\": \"malicious-domain.com\", \"src_ip\": \"10.0.2.15\", \"count\": 15},\n",
        "                {\"timestamp\": \"2024-01-15 09:02:00\", \"query\": \"google.com\", \"src_ip\": \"192.168.1.50\", \"count\": 120},\n",
        "                {\"timestamp\": \"2024-01-15 09:03:00\", \"query\": \"EJFDEBFEEBFACACACACACACACACAAA\", \"src_ip\": \"10.0.2.15\", \"count\": 8},\n",
        "                {\"timestamp\": \"2024-01-15 09:04:00\", \"query\": \"microsoft.com\", \"src_ip\": \"192.168.1.100\", \"count\": 45}\n",
        "            ],\n",
        "            'http': [\n",
        "                {\"timestamp\": \"2024-01-15 10:00:00\", \"src_ip\": \"192.168.1.100\", \"method\": \"GET\",\n",
        "                 \"url\": \"/admin.php\", \"status\": 200, \"user_agent\": \"Mozilla/5.0\"},\n",
        "                {\"timestamp\": \"2024-01-15 10:01:00\", \"src_ip\": \"10.0.2.15\", \"method\": \"POST\",\n",
        "                 \"url\": \"/login.php\", \"status\": 403, \"user_agent\": \"sqlmap/1.6\"},\n",
        "                {\"timestamp\": \"2024-01-15 10:02:00\", \"src_ip\": \"203.0.113.45\", \"method\": \"GET\",\n",
        "                 \"url\": \"/wp-admin\", \"status\": 404, \"user_agent\": \"Nikto/2.1.6\"}\n",
        "            ]\n",
        "        }\n",
        "\n",
        "    def _analyze_winevent_logs(self, df: pd.DataFrame) -> List[Threat]:\n",
        "        \"\"\"Анализ Windows Event Logs\"\"\"\n",
        "        threats = []\n",
        "\n",
        "        # Поиск подозрительных EventID\n",
        "        suspicious_events = df[df['event_id'].isin(self.config['suspicious_event_ids'])]\n",
        "\n",
        "        for _, event in suspicious_events.iterrows():\n",
        "            # Особенно подозрительны множественные неудачные входы\n",
        "            if event['event_id'] == 4625 and event.get('count', 0) > self.config['max_failed_logins']:\n",
        "                threat_id = hashlib.md5(f\"failed-login-{event['source_ip']}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"Brute Force Attack\",\n",
        "                    severity=\"High\",\n",
        "                    source_ip=event['source_ip'],\n",
        "                    target=\"Windows Authentication\",\n",
        "                    description=f\"Множественные неудачные попытки входа: {event['count']} попыток\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=85,\n",
        "                    source_data=\"Windows Event Logs\"\n",
        "                )\n",
        "                threats.append(threat)\n",
        "\n",
        "            # Очистка журналов аудита - очень подозрительно\n",
        "            elif event['event_id'] == 1102:\n",
        "                threat_id = hashlib.md5(f\"log-clear-{event['source_ip']}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"Log Tampering\",\n",
        "                    severity=\"Critical\",\n",
        "                    source_ip=event['source_ip'],\n",
        "                    target=\"Audit Logs\",\n",
        "                    description=\"Очистка журналов аудита (попытка скрыть следы)\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=90,\n",
        "                    source_data=\"Windows Event Logs\"\n",
        "                )\n",
        "                threats.append(threat)\n",
        "\n",
        "        return threats\n",
        "\n",
        "    def _analyze_dns_logs(self, df: pd.DataFrame) -> List[Threat]:\n",
        "        #Анализ DNS логов\n",
        "        threats = []\n",
        "\n",
        "        for _, dns_query in df.iterrows():\n",
        "            query = dns_query['query']\n",
        "            count = dns_query.get('count', 1)\n",
        "\n",
        "            # Проверка на DNS туннелирование (длинные/случайные имена)\n",
        "            if len(query) > 30 and re.match(r'^[A-Z]+$', query):\n",
        "                threat_id = hashlib.md5(f\"dns-tunnel-{query}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"DNS Tunneling\",\n",
        "                    severity=\"Medium\",\n",
        "                    source_ip=dns_query['src_ip'],\n",
        "                    target=query,\n",
        "                    description=f\"Подозрительный DNS запрос (возможное туннелирование): {query}\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=75,\n",
        "                    source_data=\"DNS Logs\"\n",
        "                )\n",
        "                threats.append(threat)\n",
        "\n",
        "            # Чрезмерное количество запросов\n",
        "            elif count > self.config['high_dns_query_threshold']:\n",
        "                threat_id = hashlib.md5(f\"dns-flood-{query}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"DNS Flood\",\n",
        "                    severity=\"Low\",\n",
        "                    source_ip=dns_query['src_ip'],\n",
        "                    target=query,\n",
        "                    description=f\"Чрезмерное количество DNS запросов: {count} запросов\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=65,\n",
        "                    source_data=\"DNS Logs\"\n",
        "                )\n",
        "                threats.append(threat)\n",
        "\n",
        "        return threats\n",
        "\n",
        "    def _analyze_http_logs(self, df: pd.DataFrame) -> List[Threat]:\n",
        "        \"\"\"Анализ HTTP логов\"\"\"\n",
        "        threats = []\n",
        "\n",
        "        for _, http_log in df.iterrows():\n",
        "            user_agent = http_log.get('user_agent', '')\n",
        "            url = http_log.get('url', '')\n",
        "\n",
        "            # Проверка на подозрительные User-Agent\n",
        "            for suspicious in self.config['suspicious_user_agents']:\n",
        "                if suspicious.lower() in user_agent.lower():\n",
        "                    threat_id = hashlib.md5(f\"suspicious-ua-{http_log['src_ip']}\".encode()).hexdigest()[:8]\n",
        "                    threat = Threat(\n",
        "                        id=threat_id,\n",
        "                        type=\"Scanner/Exploit Tool\",\n",
        "                        severity=\"Medium\",\n",
        "                        source_ip=http_log['src_ip'],\n",
        "                        target=url,\n",
        "                        description=f\"Обнаружен инструмент сканирования/взлома: {user_agent}\",\n",
        "                        timestamp=datetime.now(),\n",
        "                        confidence=80,\n",
        "                        source_data=\"HTTP Logs\"\n",
        "                    )\n",
        "                    threats.append(threat)\n",
        "                    break\n",
        "\n",
        "            # Проверка на доступ к административным интерфейсам\n",
        "            admin_paths = ['/admin', '/wp-admin', '/administrator', '/manage']\n",
        "            if any(path in url.lower() for path in admin_paths):\n",
        "                threat_id = hashlib.md5(f\"admin-access-{http_log['src_ip']}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"Admin Interface Access\",\n",
        "                    severity=\"Low\",\n",
        "                    source_ip=http_log['src_ip'],\n",
        "                    target=url,\n",
        "                    description=f\"Доступ к административному интерфейсу: {url}\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=60,\n",
        "                    source_data=\"HTTP Logs\"\n",
        "                )\n",
        "                threats.append(threat)\n",
        "\n",
        "        return threats\n",
        "\n",
        "    # РЕАГИРОВАНИЕ НА УГРОЗЫ\n",
        "\n",
        "    def respond_to_threat(self, threat: Threat) -> Dict[str, Any]:\n",
        "        \"\"\"Реагирование на обнаруженную угрозу\"\"\"\n",
        "        try:\n",
        "            # Определение действия на основе серьезности\n",
        "            if threat.severity in [\"Critical\", \"High\"]:\n",
        "                action = \"block_ip\"\n",
        "                action_desc = f\"Блокировка IP {threat.source_ip}\"\n",
        "                if threat.source_ip not in ['Unknown', 'DNS Client', 'Scanner']:\n",
        "                    self.blocked_ips.append(threat.source_ip)\n",
        "\n",
        "                # Проверка IP через VirusTotal перед блокировкой\n",
        "                vt_check = self.check_virustotal(threat.source_ip)\n",
        "                if vt_check['success'] and vt_check['malicious'] >= self.config['min_malicious_score']:\n",
        "                    action_desc += f\" (подтверждено VirusTotal: {vt_check['malicious']} детектов)\"\n",
        "\n",
        "            elif threat.severity == \"Medium\":\n",
        "                action = \"alert\"\n",
        "                action_desc = f\"Уведомление SOC об угрозе {threat.id}\"\n",
        "            else:\n",
        "                action = \"monitor\"\n",
        "                action_desc = f\"Мониторинг активности {threat.source_ip}\"\n",
        "\n",
        "            logger.warning(f\"РЕАГИРОВАНИЕ: {action_desc}\")\n",
        "\n",
        "            return {\n",
        "                'success': True,\n",
        "                'threat_id': threat.id,\n",
        "                'action': action,\n",
        "                'action_description': action_desc,\n",
        "                'timestamp': datetime.now().isoformat(),\n",
        "                'blocked_ip': threat.source_ip if action == \"block_ip\" and threat.source_ip not in ['Unknown', 'DNS Client', 'Scanner'] else None\n",
        "            }\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка реагирования: {e}\")\n",
        "            return {'success': False, 'error': str(e)}\n",
        "\n",
        "    # ========== ГЕНЕРАЦИЯ ОТЧЕТОВ ==========\n",
        "\n",
        "    def generate_report(self, all_threats: List[Threat]) -> Dict[str, Any]:\n",
        "        \"\"\"Генерация отчета в формате JSON и CSV\"\"\"\n",
        "        try:\n",
        "            # Подготовка данных для JSON\n",
        "            report_data = {\n",
        "                'report_generated': datetime.now().isoformat(),\n",
        "                'total_threats_detected': len(all_threats),\n",
        "                'threats_by_severity': {},\n",
        "                'threats_by_type': {},\n",
        "                'blocked_ips': self.blocked_ips,\n",
        "                'threat_details': [],\n",
        "                'summary': {\n",
        "                    'critical_count': 0,\n",
        "                    'high_count': 0,\n",
        "                    'medium_count': 0,\n",
        "                    'low_count': 0\n",
        "                }\n",
        "            }\n",
        "\n",
        "            # Анализ угроз\n",
        "            for threat in all_threats:\n",
        "                # По серьезности\n",
        "                report_data['threats_by_severity'][threat.severity] = \\\n",
        "                    report_data['threats_by_severity'].get(threat.severity, 0) + 1\n",
        "\n",
        "                # По типу\n",
        "                report_data['threats_by_type'][threat.type] = \\\n",
        "                    report_data['threats_by_type'].get(threat.type, 0) + 1\n",
        "\n",
        "                # Счетчики для summary\n",
        "                if threat.severity == \"Critical\":\n",
        "                    report_data['summary']['critical_count'] += 1\n",
        "                elif threat.severity == \"High\":\n",
        "                    report_data['summary']['high_count'] += 1\n",
        "                elif threat.severity == \"Medium\":\n",
        "                    report_data['summary']['medium_count'] += 1\n",
        "                elif threat.severity == \"Low\":\n",
        "                    report_data['summary']['low_count'] += 1\n",
        "\n",
        "                # Детали угрозы\n",
        "                threat_dict = {\n",
        "                    'id': threat.id,\n",
        "                    'type': threat.type,\n",
        "                    'severity': threat.severity,\n",
        "                    'source_ip': threat.source_ip,\n",
        "                    'target': threat.target,\n",
        "                    'description': threat.description,\n",
        "                    'timestamp': threat.timestamp.isoformat(),\n",
        "                    'confidence': threat.confidence,\n",
        "                    'indicators': threat.indicators,\n",
        "                    'source_data': threat.source_data\n",
        "                }\n",
        "                report_data['threat_details'].append(threat_dict)\n",
        "\n",
        "            # Сохранение в JSON\n",
        "            with open('security_report.json', 'w', encoding='utf-8') as f:\n",
        "                json.dump(report_data, f, indent=2, ensure_ascii=False, default=str)\n",
        "\n",
        "            # Сохранение в CSV с помощью pandas\n",
        "            if all_threats:\n",
        "                df_data = []\n",
        "                for threat in all_threats:\n",
        "                    df_data.append({\n",
        "                        'Threat_ID': threat.id,\n",
        "                        'Type': threat.type,\n",
        "                        'Severity': threat.severity,\n",
        "                        'Source_IP': threat.source_ip,\n",
        "                        'Target': threat.target,\n",
        "                        'Confidence': threat.confidence,\n",
        "                        'Timestamp': threat.timestamp,\n",
        "                        'Description': threat.description,\n",
        "                        'Source_Data': threat.source_data\n",
        "                    })\n",
        "\n",
        "                df = pd.DataFrame(df_data)\n",
        "                df.to_csv('security_report.csv', index=False, encoding='utf-8')\n",
        "\n",
        "            logger.info(f\"Отчет сгенерирован: {len(all_threats)} угроз\")\n",
        "            return report_data\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка генерации отчета: {e}\")\n",
        "            return {'success': False, 'error': str(e)}\n",
        "\n",
        "    def create_visualization(self, all_threats: List[Threat]):\n",
        "        \"\"\"Создание визуализации угроз с matplotlib/seaborn\"\"\"\n",
        "        try:\n",
        "            if not all_threats:\n",
        "                logger.warning(\"Нет данных для визуализации\")\n",
        "                return\n",
        "\n",
        "            # Подготовка данных\n",
        "            threat_types = [t.type for t in all_threats]\n",
        "            severity_levels = [t.severity for t in all_threats]\n",
        "\n",
        "            # Создание графика с 1 строкой и 2 колонками\n",
        "            fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
        "            fig.suptitle('Анализ угроз безопасности', fontsize=16, fontweight='bold')\n",
        "\n",
        "            # 1. Распределение по типу угроз\n",
        "            if threat_types:\n",
        "                type_counts = pd.Series(threat_types).value_counts()\n",
        "                bars = axes[0].bar(type_counts.index, type_counts.values,\n",
        "                                   color=['#ff6b6b', '#4ecdc4', '#45b7d1', '#ffd166', '#ef476f', '#118ab2'])\n",
        "                axes[0].set_title('Типы обнаруженных угроз', fontsize=12)\n",
        "                axes[0].set_ylabel('Количество', fontsize=10)\n",
        "                axes[0].tick_params(axis='x', rotation=45, labelsize=9)\n",
        "                axes[0].grid(axis='y', alpha=0.3)\n",
        "\n",
        "                # Добавление значений над столбцами\n",
        "                for bar in bars:\n",
        "                    height = bar.get_height()\n",
        "                    axes[0].text(bar.get_x() + bar.get_width()/2., height,\n",
        "                                f'{int(height)}', ha='center', va='bottom', fontsize=9)\n",
        "\n",
        "            # 2. Распределение по серьезности\n",
        "            if severity_levels:\n",
        "                severity_counts = pd.Series(severity_levels).value_counts()\n",
        "                colors = {'Critical': '#ff0000', 'High': '#ff6b6b', 'Medium': '#ffd166', 'Low': '#06d6a0'}\n",
        "                severity_colors = [colors.get(s, '#999999') for s in severity_counts.index]\n",
        "\n",
        "                wedges, texts, autotexts = axes[1].pie(\n",
        "                    severity_counts.values,\n",
        "                    labels=severity_counts.index,\n",
        "                    colors=severity_colors,\n",
        "                    autopct='%1.1f%%',\n",
        "                    startangle=90,\n",
        "                    textprops={'fontsize': 9}\n",
        "                )\n",
        "                axes[1].set_title('Распределение по серьезности', fontsize=12)\n",
        "\n",
        "                # Настройка отображения процентов\n",
        "                for autotext in autotexts:\n",
        "                    autotext.set_color('white')\n",
        "                    autotext.set_fontweight('bold')\n",
        "\n",
        "            plt.tight_layout()\n",
        "            plt.savefig('threat_analysis.png', dpi=150, bbox_inches='tight')\n",
        "            plt.close()\n",
        "\n",
        "            logger.info(\"Визуализация сохранена в threat_analysis.png\")\n",
        "\n",
        "        except Exception as e:\n",
        "            logger.error(f\"Ошибка создания визуализации: {e}\")\n",
        "\n",
        "    def run_security_analysis(self):\n",
        "        #Метод запуска анализа безопасности\n",
        "        logger.info(\"ЗАПУСК АНАЛИЗА БЕЗОПАСНОСТИ\")\n",
        "\n",
        "        all_threats = []\n",
        "        response_actions = []\n",
        "\n",
        "        # Анализ через VirusTotal API\n",
        "        logger.info(\"\\n1. АНАЛИЗ ЧЕРЕЗ VIRUSTOTAL API...\")\n",
        "        test_ips = [\"185.220.101.33\", \"192.168.1.100\", \"8.8.8.8\", \"10.0.2.15\"]\n",
        "        for ip in test_ips:\n",
        "            vt_result = self.check_virustotal(ip)\n",
        "            if vt_result['success'] and vt_result['malicious'] >= self.config['min_malicious_score']:\n",
        "                threat_id = hashlib.md5(f\"vt-{ip}\".encode()).hexdigest()[:8]\n",
        "                threat = Threat(\n",
        "                    id=threat_id,\n",
        "                    type=\"Malicious IP\",\n",
        "                    severity=\"High\" if vt_result['malicious'] > 10 else \"Medium\",\n",
        "                    source_ip=ip,\n",
        "                    target=\"Network\",\n",
        "                    description=f\"Вредоносный IP обнаружен: {ip} (malicious: {vt_result['malicious']}, tags: {', '.join(vt_result.get('tags', []))})\",\n",
        "                    timestamp=datetime.now(),\n",
        "                    confidence=vt_result['malicious'] * 10,\n",
        "                    source_data=\"VirusTotal API\"\n",
        "                )\n",
        "                all_threats.append(threat)\n",
        "\n",
        "        # Анализ HTTP трафика\n",
        "        logger.info(\"\\n2. АНАЛИЗ HTTP ТРАФИКА...\")\n",
        "        http_analysis = self.analyze_http_traffic(\"http://example.com\")\n",
        "        if http_analysis['success']:\n",
        "            all_threats.extend(http_analysis['threats'])\n",
        "\n",
        "        # Анализ логов безопасности\n",
        "        logger.info(\"\\n3. АНАЛИЗ ЛОГОВ БЕЗОПАСНОСТИ...\")\n",
        "        log_analysis = self.analyze_security_logs()\n",
        "        if log_analysis['success']:\n",
        "            all_threats.extend(log_analysis['threats'])\n",
        "\n",
        "        # Реагирование на угрозы\n",
        "        logger.info(\"\\n4. РЕАГИРОВАНИЕ НА УГРОЗЫ...\")\n",
        "        for threat in all_threats:\n",
        "            response = self.respond_to_threat(threat)\n",
        "            if response['success']:\n",
        "                response_actions.append(response)\n",
        "\n",
        "        # Генерация отчетов\n",
        "        logger.info(\"\\n5. ГЕНЕРАЦИЯ ОТЧЕТОВ...\")\n",
        "        report = self.generate_report(all_threats)\n",
        "\n",
        "        # Создание визуализации\n",
        "        logger.info(\"\\n6. СОЗДАНИЕ ВИЗУАЛИЗАЦИИ...\")\n",
        "        self.create_visualization(all_threats)\n",
        "\n",
        "        # Вывод итогов\n",
        "        logger.info(\"\\n \\nИТОГИ АНАЛИЗА БЕЗОПАСНОСТИ\")\n",
        "        logger.info(f\"Всего обнаружено угроз: {len(all_threats)}\")\n",
        "        logger.info(f\"Заблокировано IP: {len(self.blocked_ips)}\")\n",
        "        logger.info(f\"Выполнено действий: {len(response_actions)}\")\n",
        "\n",
        "        if all_threats:\n",
        "            severity_counts = {}\n",
        "            for threat in all_threats:\n",
        "                severity_counts[threat.severity] = severity_counts.get(threat.severity, 0) + 1\n",
        "\n",
        "            logger.info(\"\\nРаспределение по серьезности:\")\n",
        "            for severity in ['Critical', 'High', 'Medium', 'Low']:\n",
        "                if severity in severity_counts:\n",
        "                    logger.info(f\"  {severity}: {severity_counts[severity]}\")\n",
        "\n",
        "        return {\n",
        "            'total_threats': len(all_threats),\n",
        "            'blocked_ips': self.blocked_ips,\n",
        "            'response_actions': len(response_actions),\n",
        "            'report_generated': bool(report),\n",
        "            'files_created': ['security_report.json', 'security_report.csv', 'threat_analysis.png']\n",
        "        }\n",
        "\n",
        "\n",
        "def main():\n",
        "    # Функция запуска системы\n",
        "    print(\"\\n СИСТЕМА МОНИТОРИНГА И РЕАГИРОВАНИЯ НА УГРОЗЫ \\n\")\n",
        "    print(\"Используемые источники данных:\")\n",
        "    print(\"1. VirusTotal API - анализ репутации IP\")\n",
        "    print(\"2. HTTP Analysis - анализ веб-трафика\")\n",
        "    print(\"3. Security Logs - анализ логов Windows/DNS/HTTP \\n\")\n",
        "\n",
        "    # Проверка зависимостей\n",
        "    try:\n",
        "        import requests, pandas, matplotlib, seaborn\n",
        "    except ImportError as e:\n",
        "        print(f\"Ошибка: отсутствуют необходимые библиотеки: {e}\")\n",
        "        print(\"Установите их командой: pip install requests pandas matplotlib seaborn\")\n",
        "        return\n",
        "\n",
        "    # Запуск анализа\n",
        "    monitor = SecurityMonitor(use_demo=True)\n",
        "    results = monitor.run_security_analysis()\n",
        "\n",
        "    # Вывод результатов\n",
        "    print(\"\\nРЕЗУЛЬТАТЫ ВЫПОЛНЕНИЯ:\")\n",
        "    print(f\"Обнаружено угроз: {results['total_threats']}\")\n",
        "    print(f\"Заблокировано IP: {len(results['blocked_ips'])}\")\n",
        "\n",
        "    if results['blocked_ips']:\n",
        "        print(f\"Заблокированные адреса: {', '.join(results['blocked_ips'][:3])}\")\n",
        "\n",
        "    print(f\"Создано файлов отчета: {len(results['files_created'])}\")\n",
        "\n",
        "    return results\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}